dataset: kth

dataset_path: data/kth


# General Hyperparams
epochs: 50

batch_size: 32

learning_rate: 0.001


# LR warmup
warmup_init_lr: 0

warmup_epochs: 10

# Seq information
seq_len: 10

prediction_len: 10


# Scheduler
factor: 0.1

patience: 10


# Logging
log_freq: 100

save_freq: 5

# Paths
save_path: "models/kth"

result_path: "results/kth"